working_directory: &working_directory
  ~/project

defaults: &defaults
  docker:
    - image: circleci/python:3.7.2-stretch-node
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
  deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: *repo_cache_key
      - run:
          name: prepare environment
          command: make venv
      - save_cache:
          paths:
            - ./venv
          key: *repo_cache_key
      - persist_to_workspace:
          root: *working_directory
          paths: venv/*

  update:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - add_ssh_keys:
          fingerprints:
            - "30:7d:5e:d4:84:c7:03:18:c7:64:bc:67:11:50:b1:b5"
      - run:
          name: Configure git
          command: |
            git config --global user.email "circleci@scrapd.org"
            git config --global user.name "CircleCI"
      - run:
          name: Update data sets.
          command: |
            sudo apt-get update -qq
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq --no-install-recommends jq
            source venv/bin/activate
            bash .circleci/update-datasets.sh

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 13 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 14 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 18 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 19 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 21 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 22 * * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - prepare
      - update:
          requires:
            - prepare

